# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "755d7db35414adb47973aea5df9e2077"
name = "valiram-custom-app"
handle = "valiram-custom-app"
application_url = "https://cars-atlantic-princess-economic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ranotestpooja.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_merchant_managed_fulfillment_orders,read_metaobjects,read_orders,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://cars-atlantic-princess-economic.trycloudflare.com/auth/callback",
  "https://cars-atlantic-princess-economic.trycloudflare.com/auth/shopify/callback",
  "https://cars-atlantic-princess-economic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
